### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by mom666** [tomfun/BranderEAVBundle#11]
Problem with serialization on user/admin part. 
[PROFILER SCREEN](http://joxi.ru/n2YzNBGFo5z7bA) Sometimes cause [504 error](http://joxi.ru/KAgMl0Qh46dZYm) 
ACTIONS: [set-list](https://github.com/tomfun/BranderEAVBundle/blob/master/src/Controller/RestPublicController.php#L83), [group-list](https://github.com/tomfun/BranderEAVBundle/blob/master/src/Controller/RestPublicController.php#L109
)

With serialization: [set-list](http://joxi.ru/MAjMPJWh4Lb6j2), [group-list](http://joxi.ru/ZrJqL43u9W4VeA)
Without serialization: [set-list](http://joxi.ru/RmzgP58C05ebB2), [group-list](http://joxi.ru/xAee9EPCpPEovA) 

In set-list I need additional _"attributeselect_with_options"_ group to get options in AttributeSelect. 
Also, it fixes #6 issue(partially). [Before](http://joxi.ru/52aQjyoU4D74J2) [After](http://joxi.ru/KAx5PXyTM8PMNr)
With options: [set-list](http://joxi.ru/823j740uJ40Z8m)

Final profiler: [set-list](http://joxi.ru/L21j1lMu8OMXaA), [group-list](http://joxi.ru/p27Lq1zFoxzQ5A)

**Comment by tomfun** [comment]
Ok, Free to create pull request.
And add serialization group for options.
But as I understand, when for example attribute sets is serialized attributes do same:
set -> attribute -> group -> attribute**s** -> ...
Also
set -> attribute -> valu**es**

And it is the main problem I write about. And I don't get why there is so huge difference when it is serialized with manage and without. You added screenshot of [response](http://joxi.ru/LmG364ZCeY0Pym) and then of [backbone model](http://joxi.ru/RmzgP58C05ebB2), please make another screenshots that will be explain difference between API calls with and without manage flag.

I think, that we need serious refactoring for adding serialization groups, but we can try use serializer [max depth](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#limiting-serialization-depth-of-some-properties). Although I can see new features in JMS Serializer, we can try use them to limit depth.

**Comment by mom666** [comment]
Updated screenshots for [set-list](http://joxi.ru/v29JMD9u3Y5BnA) and [group-list](http://joxi.ru/MAjMPJWh4Lbpg2).

**What I need**
- Without _manage_ flag (on user part) I need only group-list url. First of all i need group class (f.e. 'main-info'), attributes. 
- On admin part I need both urls and I can use them with _manage_ flag BUT now set-list serializes without dependency with  _manage_ flag, so I want to serialize it anyway. In set-list action on admin part I need nested attributes, their options(for select and multiselect attributes), translations. (It's groups 'Default', 'attributes', 'attributeselect_with_options', 'translations').

**Comment by tomfun** [comment]
Correct me if I'm wrong:
with manage flag:
 - [sets](http://joxi.ru/MAjMPJWh4Lb6j2)
 - [groups](http://joxi.ru/ZrJqL43u9W4VeA)

without manage flag:
 - [sets](http://joxi.ru/v29JMD9u3Y5BnA)
 - [groups](http://joxi.ru/MAjMPJWh4Lbpg2)

**Comment by tomfun** [comment]
I can explain why we get *id, isFilterable, isReuired, isSortable* - there is *@Serializer\Expose()*.  
But fields: values, groups, sets don't have *expose* and have special serialization groups, so why their are serialized with context *null* (sets) and default with groups *'Default', 'translations'* (groups)?!
